web:
  container_name: gitlab
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: 'gitlab.example.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.example.com'
      gitlab_rails['initial_root_password'] = '$ROOT_PASSWORD'
  ports:
    - '$PORT_HTTP:80'
    - '$PORT_HTTPS:443'
    - '$PORT_SSH:22'
  volumes:
    - '$PATH_ETC_GITLAB:/etc/gitlab'
    - '$PATH_VAR_LOG_GITLAB:/var/log/gitlab'
    - '$PATH_VAR_OPT_GITLAB:/var/opt/gitlab'
